{
 "title": "Kafka Broker / Zookeeper Connection",
 "tags": [ "kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kafka_server_brokerstate, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Sync Connects / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_zookeeper_session_expire_listener_zookeepersyncconnectspersec{aggregate=\"OneMinute\", cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disconnects / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_zookeeper_session_expire_listener_zookeeperdisconnectspersec{aggregate=\"OneMinute\", cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read-Only Connects / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_zookeeper_session_expire_listener_zookeeperreadonlyconnectspersec{aggregate=\"OneMinute\", cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Session Expires / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kafka_zookeeper_session_expire_listener_zookeeperexpirespersec{aggregate=\"OneMinute\", cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Auth Failures / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kafka_zookeeper_session_expire_listener_zookeeperauthfailurespersec{aggregate=\"OneMinute\", cluster=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}