{
 "title": "Kafka Consumers / Fetch Rate & Records Lag",
 "tags": [
  "kafka",
  "clients"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kafka_server_brokerstate, cluster)"
   },
   {
    "name": "env",
    "label": "env",
    "query": "label_values(kafka_consumer_fetch_manager_metrics_records_consumed_rate, env)"
   },
   {
    "name": "topic",
    "label": "topic",
    "query": "label_values(kafka_consumer_fetch_manager_metrics_records_consumed_rate, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer Client Lag",
   "type": "graph",
   "description": "The latest lag of each client",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_metrics_records_lag{env=\"$env\", topic=\"$topic\"}) by(topic, client_id, instance)",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Fetch Bytes Per Request",
   "type": "graph",
   "description": "The average number of bytes fetched per request for a topic",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_metrics_fetch_size_avg{env=\"$env\", topic=\"$topic\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Consumed Bytes Rate Per Second",
   "type": "graph",
   "description": "The average number of bytes consumed per second",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_metrics_bytes_consumed_rate{env=\"$env\", topic=\"$topic\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Consumed Records Rate Per Second",
   "type": "graph",
   "description": "The average number of records consumed per second",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_metrics_records_consumed_rate{env=\"$env\", topic=\"$topic\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  }
 ]
}