clusters = source, mirror

source.bootstrap.servers = kafka-1:9092,kafka-2:9092,kafka-3:9092
source.security.protocol = SSL
source.ssl.truststore.location = /etc/kafka/certs/kafka.truststore.jks
source.ssl.truststore.password = truststore_password
source.ssl.truststore.type = JKS

mirror.bootstrap.servers = kafka-mirror-1:9092,kafka-mirror-2:9092,kafka-mirror-3:9092
mirror.security.protocol = SSL
mirror.ssl.truststore.location = /etc/kafka/certs/kafka.truststore.jks
mirror.ssl.truststore.password = truststore_password
mirror.ssl.truststore.type = JKS

source->mirror.enabled = true
source->mirror.topics = shop-products-raw,shop-products-filtered,shop-blocker,shop-blocker-table,client-requests

source->mirror.emit.heartbeats.enabled = true
source->mirror.emit.checkpoints.enabled = true

mirror->source.enabled = false
mirror->source.emit.heartbeats.enabled = false
mirror->source.emit.checkpoints.enabled = false

replication.factor = 2
checkpoints.topic.replication.factor = 2
heartbeats.topic.replication.factor = 2
offset-syncs.topic.replication.factor = 2
offset.storage.replication.factor = 2
status.storage.replication.factor = 2
config.storage.replication.factor = 2
