package product

import (
	"encoding/json"
	"fmt"

	"github.com/confluentinc/confluent-kafka-go/v2/schemaregistry"
	"github.com/confluentinc/confluent-kafka-go/v2/schemaregistry/serde"
	"github.com/confluentinc/confluent-kafka-go/v2/schemaregistry/serde/jsonschema"
)

type Price struct {
	Amount   float64 `json:"amount"`
	Currency string  `json:"currency"`
}

type Stock struct {
	Available int `json:"available"`
	Reserved  int `json:"reserved"`
}

type Image struct {
	URL string `json:"url"`
	Alt string `json:"alt"`
}

type Specifications struct {
	Weight          string `json:"weight"`
	Dimensions      string `json:"dimensions"`
	BatteryLife     string `json:"battery_life"`
	WaterResistance string `json:"water_resistance"`
}

type Product struct {
	ProductID      string         `json:"product_id"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	Price          Price          `json:"price"`
	Category       string         `json:"category"`
	Brand          string         `json:"brand"`
	Stock          Stock          `json:"stock"`
	SKU            string         `json:"sku"`
	Tags           []string       `json:"tags"`
	Images         []Image        `json:"images"`
	Specifications Specifications `json:"specifications"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
	Index          string         `json:"index"`
	StoreID        string         `json:"store_id"`
}

// ProductPayload is the flat wire representation used with the schema registry.
// Nested/slice fields are JSON-encoded strings to match the Postgres TEXT columns.
type ProductPayload struct {
	ProductID      string `json:"product_id"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	Price          string `json:"price"`
	Category       string `json:"category"`
	Brand          string `json:"brand"`
	Stock          string `json:"stock"`
	SKU            string `json:"sku"`
	Tags           string `json:"tags"`
	Images         string `json:"images"`
	Specifications string `json:"specifications"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
	Index          string `json:"index"`
	StoreID        string `json:"store_id"`
}

func productToPayload(p *Product) (ProductPayload, error) {
	mustJSON := func(v any) (string, error) {
		b, err := json.Marshal(v)
		return string(b), err
	}

	price, err := mustJSON(p.Price)
	if err != nil {
		return ProductPayload{}, err
	}
	stock, err := mustJSON(p.Stock)
	if err != nil {
		return ProductPayload{}, err
	}
	tags, err := mustJSON(p.Tags)
	if err != nil {
		return ProductPayload{}, err
	}
	images, err := mustJSON(p.Images)
	if err != nil {
		return ProductPayload{}, err
	}
	specs, err := mustJSON(p.Specifications)
	if err != nil {
		return ProductPayload{}, err
	}

	return ProductPayload{
		ProductID:      p.ProductID,
		Name:           p.Name,
		Description:    p.Description,
		Price:          price,
		Category:       p.Category,
		Brand:          p.Brand,
		Stock:          stock,
		SKU:            p.SKU,
		Tags:           tags,
		Images:         images,
		Specifications: specs,
		CreatedAt:      p.CreatedAt,
		UpdatedAt:      p.UpdatedAt,
		Index:          p.Index,
		StoreID:        p.StoreID,
	}, nil
}

func payloadToProduct(pl ProductPayload) (*Product, error) {
	p := &Product{
		ProductID:   pl.ProductID,
		Name:        pl.Name,
		Description: pl.Description,
		Category:    pl.Category,
		Brand:       pl.Brand,
		SKU:         pl.SKU,
		CreatedAt:   pl.CreatedAt,
		UpdatedAt:   pl.UpdatedAt,
		Index:       pl.Index,
		StoreID:     pl.StoreID,
	}

	if err := json.Unmarshal([]byte(pl.Price), &p.Price); err != nil {
		return nil, fmt.Errorf("unmarshal price: %w", err)
	}
	if err := json.Unmarshal([]byte(pl.Stock), &p.Stock); err != nil {
		return nil, fmt.Errorf("unmarshal stock: %w", err)
	}
	if err := json.Unmarshal([]byte(pl.Tags), &p.Tags); err != nil {
		return nil, fmt.Errorf("unmarshal tags: %w", err)
	}
	if err := json.Unmarshal([]byte(pl.Images), &p.Images); err != nil {
		return nil, fmt.Errorf("unmarshal images: %w", err)
	}
	if err := json.Unmarshal([]byte(pl.Specifications), &p.Specifications); err != nil {
		return nil, fmt.Errorf("unmarshal specifications: %w", err)
	}

	return p, nil
}

// Draft 07 schema — Schema Registry 7.6 does not support Draft 2020-12
// generated by invopop/jsonschema by default.
const productPayloadSchemaDraft7 = `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ProductPayload",
  "type": "object",
  "additionalProperties": false,
  "required": ["product_id","name","description","price","category","brand","stock","sku","tags","images","specifications","created_at","updated_at","index","store_id"],
  "properties": {
    "product_id":      {"type": "string"},
    "name":            {"type": "string"},
    "description":     {"type": "string"},
    "price":           {"type": "string"},
    "category":        {"type": "string"},
    "brand":           {"type": "string"},
    "stock":           {"type": "string"},
    "sku":             {"type": "string"},
    "tags":            {"type": "string"},
    "images":          {"type": "string"},
    "specifications":  {"type": "string"},
    "created_at":      {"type": "string"},
    "updated_at":      {"type": "string"},
    "index":           {"type": "string"},
    "store_id":        {"type": "string"}
  }
}`

type Codec struct {
	topic string
	ser   *jsonschema.Serializer
	deser *jsonschema.Deserializer
}

func NewCodec(topic, srURL string) (*Codec, error) {
	client, err := schemaregistry.NewClient(schemaregistry.NewConfig(srURL))
	if err != nil {
		return nil, fmt.Errorf("schema registry client: %w", err)
	}

	subject := topic + "-value"
	_, err = client.Register(subject, schemaregistry.SchemaInfo{
		Schema:     productPayloadSchemaDraft7,
		SchemaType: "JSON",
	}, false)
	if err != nil {
		return nil, fmt.Errorf("register schema for %s: %w", subject, err)
	}

	serCfg := jsonschema.NewSerializerConfig()
	serCfg.AutoRegisterSchemas = false
	serCfg.UseLatestVersion = true
	ser, err := jsonschema.NewSerializer(client, serde.ValueSerde, serCfg)
	if err != nil {
		return nil, fmt.Errorf("jsonschema serializer: %w", err)
	}

	deser, err := jsonschema.NewDeserializer(client, serde.ValueSerde, jsonschema.NewDeserializerConfig())
	if err != nil {
		return nil, fmt.Errorf("jsonschema deserializer: %w", err)
	}

	return &Codec{topic: topic, ser: ser, deser: deser}, nil
}

func (c *Codec) Encode(value any) ([]byte, error) {
	p, ok := value.(*Product)
	if !ok {
		return nil, fmt.Errorf("тип должен быть *Product, получен %T", value)
	}

	payload, err := productToPayload(p)
	if err != nil {
		return nil, fmt.Errorf("encode payload: %w", err)
	}

	return c.ser.Serialize(c.topic, &payload)
}

func (c *Codec) Decode(data []byte) (any, error) {
	var payload ProductPayload
	if err := c.deser.DeserializeInto(c.topic, data, &payload); err != nil {
		return nil, fmt.Errorf("deserialize: %w", err)
	}

	return payloadToProduct(payload)
}
