listeners=http://0.0.0.0:8081
host.name=schema-registry

kafkastore.bootstrap.servers=SSL://kafka-1:9092,SSL://kafka-2:9092,SSL://kafka-3:9092
kafkastore.security.protocol=SSL
kafkastore.ssl.truststore.location=/opt/bitnami/schema-registry/certs/schema-registry.truststore.jks
kafkastore.ssl.truststore.password=truststore_password
kafkastore.ssl.truststore.type=PKCS12
kafkastore.ssl.cipher.suites=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
kafkastore.ssl.endpoint.identification.algorithm=

schema.compatibility.level=backward
debug=false
