global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'kafka'
    static_configs:
    - targets:
      - 'jmx-kafka-1:5556'
      - 'jmx-kafka-2:5556'
      - 'jmx-kafka-3:5556'
      - 'jmx-kafka-mirror-1:5556'
      - 'jmx-kafka-mirror-2:5556'
      - 'jmx-kafka-mirror-3:5556'

  - job_name: 'kafka-connect'
    static_configs:
    - targets:
      - 'kafka-connect:9876'

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
